### Register
POST http://{{base_url}}/register
Content-Type: application/json

{
  "username": "devops",
  "password": "devops"
}

### Login
POST http://{{base_url}}/login
Content-Type: application/json

{
  "username": "devops",
  "password": "devops"
}
