version: '3.9'

volumes:
  postgres_data:


services:
  postgres:
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_PASSWORD=devops
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-stuble:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
     - postgres
