### Add Entry
POST http://{{base_url}}/api/entry
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "content": "Test"
}

### Get Entries
GET http://{{base_url}}/api/entry
Authorization: Bearer {{auth_token}}
Content-Type: application/json

